const brands2 = [
    {
      city: 'Home & Deco.',
      country: 'LEVIS',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTikV73-_9P2UUWj3rKg-TmgjrxGPmUO-BdOw&usqp=CAU',
    },
    {
      city: 'Shop - Gadgets',
      country: 'REEBOK',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Reebok_logo19.png',
    },
    {
      city: 'Chanel',
      country: 'Milan ladies striped',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.globalbrandsmagazine.com/wp-content/uploads/2021/06/990__1513770089_693_chanel1_3f16706be8a9-2.png',
    },
    {
      city: 'Schneider Electric',
      country: 'ladies striped T-SHIRT',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'http://www.psuconnect.in/sdsdsd/Large_enterprises,_MSMEs_Climate_Conscious_Individuals_join_Schneiders_Green_Yodha_sustainability_initiative.jpghttp://www.psuconnect.in/sdsdsd/Large_enterprises,_MSMEs_Climate_Conscious_Individuals_join_Schneiders_Green_Yodha_sustainability_initiative.jpg',
    },
    {
      city: 'IFM',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://banner2.cleanpng.com/20180622/tqe/kisspng-ifm-electronic-io-link-logo-industry-5b2d727cc3e6e5.6356919515297050848024.jpg',
    },
    {
        city: 'ACDC DYNAMICS',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://www.cbn.co.za/wp-content/uploads/2021/11/ACDC-logo.jpg',
      },
      {
        city: 'EMERSON',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Emerson_Electric_Company.svg/1200px-Emerson_Electric_Company.svg.png',
      },
      {
        city: 'ABB',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/ABB_logo.svg/2560px-ABB_logo.svg.png',
      },
      {
        city: 'SIEMENS',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://1000logos.net/wp-content/uploads/2017/06/Color-Siemens-Logo.jpg',
      },
      {
        city: 'OMRON',
        country: 'Russia',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://1000logos.net/wp-content/uploads/2021/05/Omron-logo.png',
      },
      {
        city: 'SIEMENS',
        country: 'Furniture',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://www.designyourway.net/blog/wp-content/uploads/2019/10/s1-57.jpg',
      },
      {
        city: 'FESTO',
        country: 'Tech',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://images.squarespace-cdn.com/content/v1/5d81abe36d26423737914620/1568792707355-74KQTPA8LJCZICVQNJ0U/logo-festo.png',
      },
      {
        city: 'SICK',
        country: 'Clothing',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://cdn.freebiesupply.com/logos/large/2x/sick-optic-electronic-1-logo-png-transparent.png',
      },
      {
        city: 'ROCKWELL AUTOMATION',
        country: 'Clothing',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://rockwellautomation.scene7.com/is/image/rockwellautomationstage/rockwellautomation-logo-16x9.2550.jpg',
      },
      {
        city: 'HellermannTyton',
        country: 'Russia',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://www.hellermanntyton.us/docs/default-source/ht_logos/ht_logo_rgb_screen_th.jpg',
      },
      {
          city: 'SONY',
          country: 'Furniture',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://i.pinimg.com/originals/c1/3f/4c/c13f4cef7979400dcef70136e2cec47c.jpg',
        },
        {
          city: 'HUAWEI',
          country: 'Tech',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Huawei_Standard_logo.svg/1200px-Huawei_Standard_logo.svg.png',
        },
        {
          city: 'DELL',
          country: 'Clothing',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Dell_Logo.svg/2048px-Dell_Logo.svg.png',
        },
        {
          city: 'LENOVO',
          country: 'Clothing',
          p_logo: 'https://www.misprincipes.com/A4TYGHESUYO6UOZ2/uploads/image_88396_104_20210910083828.jpg',
        },
        {
          city: 'RAIN',
          country: 'Russia',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://businesstech.co.za/news/wp-content/uploads/2017/12/Rain-USE-THIS.png',
        },
        {
          city: 'MTN',
          country: 'Furniture',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/MTN_Logo.svg/2048px-MTN_Logo.svg.png',
        },
        {
          city: 'Shop - Gadgets',
          country: 'Tech',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://weareegg.co.za/media/catalog/product/cache/cd323204adbc90346956a7797c460c7b/t/l/tlt10461_1_1.jpg',
        },
        {
          city: 'Mens',
          country: 'Clothing',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://www.eliteoccasions.co.za/content/images/thumbs/0022090_striped-button-through-shirt-dress-without-belt.jpeg',
        },
        {
          city: 'Womens',
          country: 'Clothing',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/3080020b4c/mens-crew-t-shirt.jpg',
        },
        {
          city: 'Moscow',
          country: 'Russia',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://www.yde.co.za/media/product/424/red-printed-track-pants-563.jpg',
        },
        {
            city: 'Home & Deco.',
            country: 'Furniture',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
          },
          {
            city: 'Shop - Gadgets',
            country: 'Tech',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
          },
          {
            city: 'Mens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
          },
          {
            city: 'Womens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
          {
            city: 'Home & Deco.',
            country: 'Furniture',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2020/10/13/1/CI_Ilya_Zabanov-mastersandforbes-livingroom-Image1.jpg.rend.hgtvcom.966.725.suffix/1602599983799.jpeg',
          },
          {
            city: 'Shop - Gadgets',
            country: 'Tech',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.autods.com/OfficialSite/New/20201103091044/The-Best-10-Trending-Tech-Gadgets-Dropshipping-Products-To-Sell-in-2021-1024x576.png',
          },
          {
            city: 'Mens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
          },
          {
            city: 'Womens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
          {
            city: 'Home & Deco.',
            country: 'Furniture',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2020/10/13/1/CI_Ilya_Zabanov-mastersandforbes-livingroom-Image1.jpg.rend.hgtvcom.966.725.suffix/1602599983799.jpeg',
          },
          {
            city: 'Shop - Gadgets',
            country: 'Tech',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.autods.com/OfficialSite/New/20201103091044/The-Best-10-Trending-Tech-Gadgets-Dropshipping-Products-To-Sell-in-2021-1024x576.png',
          },
          {
            city: 'Mens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
          },
          {
            city: 'Womens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
  ];

  export default brands2