const slides = [
    {
      city: 'Home & Deco.',
      country: 'summer dress',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/164857bee1/plain-strappy-tiered-dress.jpg',
    },
    {
      city: 'Shop - Gadgets',
      country: 'summer v dress',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://weareegg.co.za/media/catalog/product/cache/cd323204adbc90346956a7797c460c7b/t/l/tlt10461_1_1.jpg',
    },
    {
      city: 'Mens',
      country: 'Milan ladies striped',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.eliteoccasions.co.za/content/images/thumbs/0022090_striped-button-through-shirt-dress-without-belt.jpeg',
    },
    {
      city: 'Womens',
      country: 'ladies striped T-SHIRT',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/3080020b4c/mens-crew-t-shirt.jpg',
    },
    {
      city: 'Moscow',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.yde.co.za/media/product/424/red-printed-track-pants-563.jpg',
    },
    {
        city: 'Home & Deco.',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
      },
      {
        city: 'Shop - Gadgets',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
      },
      {
        city: 'Mens',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
      },
      {
        city: 'Womens',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
      },
      {
        city: 'Moscow',
        country: 'Russia',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
      },
      {
        city: 'Home & Deco.',
        country: 'Furniture',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2020/10/13/1/CI_Ilya_Zabanov-mastersandforbes-livingroom-Image1.jpg.rend.hgtvcom.966.725.suffix/1602599983799.jpeg',
      },
      {
        city: 'Shop - Gadgets',
        country: 'Tech',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://images.autods.com/OfficialSite/New/20201103091044/The-Best-10-Trending-Tech-Gadgets-Dropshipping-Products-To-Sell-in-2021-1024x576.png',
      },
      {
        city: 'Mens',
        country: 'Clothing',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
      },
      {
        city: 'Womens',
        country: 'Clothing',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
      },
      {
        city: 'Moscow',
        country: 'Russia',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
      },
      {
          city: 'Home & Deco.',
          country: 'Furniture',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2020/10/13/1/CI_Ilya_Zabanov-mastersandforbes-livingroom-Image1.jpg.rend.hgtvcom.966.725.suffix/1602599983799.jpeg',
        },
        {
          city: 'Shop - Gadgets',
          country: 'Tech',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://images.autods.com/OfficialSite/New/20201103091044/The-Best-10-Trending-Tech-Gadgets-Dropshipping-Products-To-Sell-in-2021-1024x576.png',
        },
        {
          city: 'Mens',
          country: 'Clothing',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
        },
        {
          city: 'Womens',
          country: 'Clothing',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
        },
        {
          city: 'Moscow',
          country: 'Russia',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
        },
        {
          city: 'Home & Deco.',
          country: 'Furniture',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/164857bee1/plain-strappy-tiered-dress.jpg',
        },
        {
          city: 'Shop - Gadgets',
          country: 'Tech',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://weareegg.co.za/media/catalog/product/cache/cd323204adbc90346956a7797c460c7b/t/l/tlt10461_1_1.jpg',
        },
        {
          city: 'Mens',
          country: 'Clothing',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://www.eliteoccasions.co.za/content/images/thumbs/0022090_striped-button-through-shirt-dress-without-belt.jpeg',
        },
        {
          city: 'Womens',
          country: 'Clothing',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/3080020b4c/mens-crew-t-shirt.jpg',
        },
        {
          city: 'Moscow',
          country: 'Russia',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://www.yde.co.za/media/product/424/red-printed-track-pants-563.jpg',
        },
        {
            city: 'Home & Deco.',
            country: 'Furniture',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
          },
          {
            city: 'Shop - Gadgets',
            country: 'Tech',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
          },
          {
            city: 'Mens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
          },
          {
            city: 'Womens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
          {
            city: 'Home & Deco.',
            country: 'Furniture',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2020/10/13/1/CI_Ilya_Zabanov-mastersandforbes-livingroom-Image1.jpg.rend.hgtvcom.966.725.suffix/1602599983799.jpeg',
          },
          {
            city: 'Shop - Gadgets',
            country: 'Tech',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.autods.com/OfficialSite/New/20201103091044/The-Best-10-Trending-Tech-Gadgets-Dropshipping-Products-To-Sell-in-2021-1024x576.png',
          },
          {
            city: 'Mens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
          },
          {
            city: 'Womens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
          {
            city: 'Home & Deco.',
            country: 'Furniture',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2020/10/13/1/CI_Ilya_Zabanov-mastersandforbes-livingroom-Image1.jpg.rend.hgtvcom.966.725.suffix/1602599983799.jpeg',
          },
          {
            city: 'Shop - Gadgets',
            country: 'Tech',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.autods.com/OfficialSite/New/20201103091044/The-Best-10-Trending-Tech-Gadgets-Dropshipping-Products-To-Sell-in-2021-1024x576.png',
          },
          {
            city: 'Mens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
          },
          {
            city: 'Womens',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
          {
            city: 'Moscow',
            country: 'Russia',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
          },
  ];

  export default slides