const brands = [
    {
      city: 'Home & Deco.',
      country: 'Nike',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://miro.medium.com/max/900/0*9hcinRdaHicrNpNE.jpg',
    },
    {
      city: 'Shop - Gadgets',
      country: 'ADIDAS',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://assets.website-files.com/5ee732bebd9839b494ff27cd/5ee732bebd9839d388ff2800_adidas-logo-e1468257076328.jpg',
    },
    {
      city: 'Chanel',
      country: 'Milan ladies striped',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.globalbrandsmagazine.com/wp-content/uploads/2021/06/990__1513770089_693_chanel1_3f16706be8a9-2.png',
    },
    {
      city: 'Schneider Electric',
      country: 'ladies striped T-SHIRT',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'http://www.psuconnect.in/sdsdsd/Large_enterprises,_MSMEs_Climate_Conscious_Individuals_join_Schneiders_Green_Yodha_sustainability_initiative.jpghttp://www.psuconnect.in/sdsdsd/Large_enterprises,_MSMEs_Climate_Conscious_Individuals_join_Schneiders_Green_Yodha_sustainability_initiative.jpg',
    },
    {
      city: 'IFM',
      country: 'Unilever',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://assets1.consumergoods.com/styles/max_width_320/s3/2018-12/Unileverlogo.jpg?itok=RVRG3xW5',
    },
    {
        city: 'ACDC DYNAMICS',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://www.cbn.co.za/wp-content/uploads/2021/11/ACDC-logo.jpg',
      },
      {
        city: 'EMERSON',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Emerson_Electric_Company.svg/1200px-Emerson_Electric_Company.svg.png',
      },
      {
        city: 'ABB',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/ABB_logo.svg/2560px-ABB_logo.svg.png',
      },
      {
        city: 'SIEMENS',
        country: 'Mens Rillogio sweater',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://1000logos.net/wp-content/uploads/2017/06/Color-Siemens-Logo.jpg',
      },
      {
        city: 'OMRON',
        country: 'Russia',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://1000logos.net/wp-content/uploads/2021/05/Omron-logo.png',
      },
      {
        city: 'SIEMENS',
        country: 'Huggies',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://s3.amazonaws.com/cdn.designcrowd.com/blog/40-Famous-Baby-Logos-That-Anyone-Can-Recognize/Huggies.jpg',
      },
      {
        city: 'FESTO',
        country: 'Cadbury',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://cdn.logojoy.com/wp-content/uploads/2018/05/01110023/299-768x591.png',
      },
      {
        city: 'SICK',
        country: 'Clothing',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://cdn.freebiesupply.com/logos/large/2x/sick-optic-electronic-1-logo-png-transparent.png',
      },
      {
        city: 'ROCKWELL AUTOMATION',
        country: 'Clothing',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://rockwellautomation.scene7.com/is/image/rockwellautomationstage/rockwellautomation-logo-16x9.2550.jpg',
      },
      {
        city: 'HellermannTyton',
        country: 'Russia',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://www.hellermanntyton.us/docs/default-source/ht_logos/ht_logo_rgb_screen_th.jpg',
      },
      {
          city: 'SONY',
          country: 'Furniture',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://i.pinimg.com/originals/c1/3f/4c/c13f4cef7979400dcef70136e2cec47c.jpg',
        },
        {
          city: 'HUAWEI',
          country: 'Tech',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Huawei_Standard_logo.svg/1200px-Huawei_Standard_logo.svg.png',
        },
        {
          city: 'DELL',
          country: 'Clothing',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Dell_Logo.svg/2048px-Dell_Logo.svg.png',
        },
        {
          city: 'LENOVO',
          country: 'Clothing',
          p_logo: 'https://www.misprincipes.com/A4TYGHESUYO6UOZ2/uploads/image_88396_104_20210910083828.jpg',
        },
        {
          city: 'RAIN',
          country: 'Russia',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://businesstech.co.za/news/wp-content/uploads/2017/12/Rain-USE-THIS.png',
        },
        {
          city: 'MTN',
          country: 'Furniture',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/MTN_Logo.svg/2048px-MTN_Logo.svg.png',
        },
        {
          city: 'Shop - Gadgets',
          country: 'BVLGARI',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://uploads-ssl.webflow.com/5f1c9cd99129705b848a815a/6123cf0a1dad320b81494d58_5.jpg',
        },
        {
          city: 'Chanel',
          country: 'PRADA',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://www.couponraja.in/theroyale/wp-content/uploads/2018/02/prada.jpg',
        },
        {
          city: 'Schneider Electric',
          country: 'VERSACE',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://www.couponraja.in/theroyale/wp-content/uploads/2018/02/versace.jpg',
        },
        {
          city: 'IFM',
          country: 'Calvin Klein',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://i.pinimg.com/originals/75/8a/c7/758ac7e2721d86e46532c9613929c462.jpg',
        },
        {
            city: 'ACDC DYNAMICS',
            country: 'FENDI',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://turbologo.com/articles/20-famous-clothing-brand-logos/',
          },
          {
            city: 'EMERSON',
            country: 'Lacoste',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://brandongaille.com/wp-content/uploads/2013/06/Lacoste-Company-Logo-Image.jpg',
          },
          {
            city: 'ABB',
            country: 'Ralph Lauren',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://uploads-ssl.webflow.com/5f1c9cd99129705b848a815a/6123d1b57de6188bb7f2a040_30.jpg',
          },
          {
            city: 'SIEMENS',
            country: 'Hollister',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://cdn.logojoy.com/wp-content/uploads/2018/05/30143419/95.png',
          },
          {
            city: 'OMRON',
            country: 'Champion',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://1000logos.net/wp-content/uploads/2019/03/Champion-logo.jpg',
          },
          {
            city: 'SIEMENS',
            country: 'louis Vuitton',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://pnggrid.com/wp-content/uploads/2021/05/Logo-Louis-Vuitton-Black-1024x786.png',
          },
          {
            city: 'FESTO',
            country: 'LEVIS',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://i.pinimg.com/736x/4e/5a/b4/4e5ab47f163378e9814e1421015cae25.jpg',
          },
          {
            city: 'SICK',
            country: 'LOREAL',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXS3OqAT79Tbm4nvU4kJxUqBcnF_9JJnvEBYiNtTW2iDcRlgsTZn4t5ygp2fRK-E_K2N4&usqp=CAU',
          },
          {
            city: 'ROCKWELL AUTOMATION',
            country: 'Clothing',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://www.investopedia.com/thmb/p5JafVrbMIfWuUhTS7Dsn8bWKts=/640x427/filters:no_upscale():max_bytes(150000):strip_icc()/All-Shampoo-Review-Garnier-1-5c744bc846e0fb0001a5eed5.jpg',
          },
          {
            city: 'HellermannTyton',
            country: 'Amplify',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://smdtechnologies.com/wp-content/uploads/2018/07/Amplifyb.jpg',
          },
          {
              city: 'SONY',
              country: 'VOLKANO',
              p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
              img: 'https://armchairshopaholic.files.wordpress.com/2021/08/dove-logo-1969.jpg',
            },
            {
              city: 'HUAWEI',
              country: 'Timberland',
              p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
              img: 'https://www.seekpng.com/png/small/343-3439713_timberland-timberland-logo-png.png',
            },
            {
              city: 'DELL',
              country: 'SALOMON',
              p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
              img: 'https://process.fs.grailed.com/AJdAgnqCST4iPtnUxiGtTz/cache=expiry:max/rotate=deg:exif/resize=width:2400,fit:crop/output=quality:70/compress/https://process.fs.grailed.com/wIV7g1q4R1jktDUK5JC0',
            },
            {
              city: 'RAIN',
              country: 'Bathu',
              p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
              img: 'https://mallofthenorth.co.za/wp-content/uploads/2022/03/bathu.jpg',
            },
            {
              city: 'MTN',
              country: 'BECKHOF',
              p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
              img: 'https://www.beckhoff.com/media/bilder/buehnen/unternehmen/beckhoff-brand.jpg',
            },
            {
              city: 'Shop - Gadgets',
              country: 'Allen Bradley',
              p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
              img: 'https://www.plc-city.com/shop/3769-large_default/rockwell-1771-cp2-nfs.jpg',
            },
            {
              city: 'Mens',
              country: 'GRAFF',
              p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
              img: 'https://1000logos.net/wp-content/uploads/2018/08/Graff-logo.jpg',
            },
            {
              city: 'Womens',
              country: 'Cartier',
              p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
              img: 'https://www.wpdiamonds.com/wp-content/uploads/2021/01/WPD-Article-Body-Images-2021-02-08T191317.673.png',
            },
            {
              city: 'Moscow',
              country: 'Lenovo',
              p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
              img: 'https://1000logos.net/wp-content/uploads/2018/08/Lenovo-logo.jpg',
            },
            {
                city: 'Home & Deco.',
                country: 'Xiomi Mi',
                p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
                img: 'https://1000logos.net/wp-content/uploads/2018/08/Xiaomi-logo.jpg',
              },
              {
                city: 'Shop - Gadgets',
                country: 'Acer',
                p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
                img: 'https://3.bp.blogspot.com/-8EDwv0QbCs4/WMz54uX8-ZI/AAAAAAAAGiM/ZonODVSOlyUw-tCqsMmB3XQC4pan6gwxACLcB/s1600/acer-mobile-brand-logo.png',
              },
              {
                city: 'Mens',
                country: 'OPPO',
                p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
                img: 'https://i.pinimg.com/550x/da/cc/87/dacc878fd251a57239f294dc72459052.jpg',
              },
              {
                city: 'Womens',
                country: 'GILLETTE',
                p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
                img: 'https://www.spar-paradies.eu/mediafiles/Bilder/Markenlogos/gillette-logo.jpg',
              },
              {
                city: 'Moscow',
                country: 'ASUS',
                p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
                img: 'https://2.bp.blogspot.com/-THY0uIrz3Bk/WMz55E7YKsI/AAAAAAAAGiU/IIasNYMN95AogNUCc1K67Bp_yVCWAdcDgCLcB/s1600/asus-mobile-brand-logo.png',
              },
              {
                city: 'Home & Deco.',
                country: 'Nivea',
                p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
                img: 'https://logos-world.net/wp-content/uploads/2020/11/Nivea-Logo-2004-2011.png',
              },
              {
                city: 'Shop - Gadgets',
                country: 'Ethereum',
                p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
                img: 'https://cryptogeek.info/resize/800x800/5daf896ab1c3e.jpeg',
              },
  ];

  export default brands