
let products = [
  {
      id: 1,
    city: 'Home & Deco.',
    country: 'Rabbit Print Cami PJ Set With Eye Cover',
    p_logo: 'https://www.designhill.com/resize_img.php?atyp=page_file&pth=ft_ca_ct||259||contestfile_1&flp=1626068668-181804171260ebd6bcf116b5-27635942.jpg',
    img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/164857bee1/plain-strappy-tiered-dress.jpg',
  },
  {
      id: 2,
    city: 'Shop - Gadgets',
    country: 'summer v dress',
    p_logo: 'https://cdn2.vectorstock.com/i/1000x1000/88/51/business-consulting-logo-icon-design-template-vector-22318851.jpg',
    img: 'https://weareegg.co.za/media/catalog/product/cache/cd323204adbc90346956a7797c460c7b/t/l/tlt10461_1_1.jpg',
  },
  {
      id: 3,
    city: 'Mens',
    country: 'Floral Lace Harness Lingerie Set',
    p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
    img: 'https://www.eliteoccasions.co.za/content/images/thumbs/0022090_striped-button-through-shirt-dress-without-belt.jpeg',
  },
  {
      id: 4,
    city: 'Womens',
    country: 'ladies striped T-SHIRT',
    p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
    img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/3080020b4c/mens-crew-t-shirt.jpg',
  },
  {
      id: 5,
    city: 'Moscow',
    country: 'Mens Rillogio sweater',
    p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
    img: 'https://www.yde.co.za/media/product/424/red-printed-track-pants-563.jpg',
  },
  {
      id: 6,
      city: 'Home & Deco.',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/164857bee1/plain-strappy-tiered-dress.jpg',
    },
    {
      id: 7,
      city: 'Shop - Gadgets',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
    },
    {
      id: 8,
      city: 'Mens',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/164857bee1/plain-strappy-tiered-dress.jpg',
    },
    {
      id: 9,
      city: 'Womens',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
    },
    {
      id: 10,
      city: 'Moscow',
      country: 'Russia',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
    },
    {
      id: 11,
      city: 'Home & Deco.',
      country: 'Furniture',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2020/10/13/1/CI_Ilya_Zabanov-mastersandforbes-livingroom-Image1.jpg.rend.hgtvcom.966.725.suffix/1602599983799.jpeg',
    },
    {
      id: 12,
      city: 'Shop - Gadgets',
      country: 'Tech',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/164857bee1/plain-strappy-tiered-dress.jpg',
    },
    {
      id: 13,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 14,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/164857bee1/plain-strappy-tiered-dress.jpg',
    },
    {
      id: 15,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/164857bee1/plain-strappy-tiered-dress.jpg',
    },
    {
      id: 16,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://5.imimg.com/data5/RU/NM/MY-5887010/electric-motor-500x500.jpg',
    },
    {
      id: 17,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Ac-elektromotor-robuster-asynchronmotor.jpg',
    },
    {
      id: 18,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 19,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 20,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 21,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 22,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 23,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 24,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://img.directindustry.com/images_di/photo-mg/25321-2481147.jpg',
    },
    {
      id: 25,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 26,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 27,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://static.dezeen.com/uploads/2022/05/ella-chair-matthew-hilton-case-furniture-design_dezeen_2364_hero.jpg',
    },
    {
      id: 28,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://craftlakecity.com/apply/profile_ajax.php?id=836&action=featured_img&size=square',
    },
    {
      id: 29,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 30,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://asianfoodnetwork.com/content/dam/afn/global/en/articles/maximise-food/AFN_grocery.jpg.transform/desktop-img/img.jpg',
    },
    {
      id: 31,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 32,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://img.freepik.com/premium-photo/shopping-bag-with-food-groceries-table-supermarket_8087-1414.jpg?w=2000',
    },
    {
      id: 33,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 34,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ2ljnS_Lxto1hrKkMbOt-Ag_y4-AuRTokABQ5WCqhahBIZLIER_FrgOrey3tPmG2tZ-M41rJtmM821CTxVqZnQqkXNlMRPQTKWnbPCrq1RXUQwBAfbRJ0MuQ&usqp=CAE',
    },
    {
      id: 35,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://5.imimg.com/data5/YY/VM/DS/SELLER-37440292/leather-ladies-purse-500x500.jpg',
    },
    {
      id: 36,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 37,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 38,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqGwnF5nXAdOeeq0AAvzerAcHceXjX6wJSulgwKA1o0jMG-awBH1nyr9JBhjcdYpr-AEU&usqp=CAU',
    },
    {
        id: 39,
      city: 'Shop - Gadgets',
      country: 'summer v dress',
      p_logo: 'https://cdn2.vectorstock.com/i/1000x1000/88/51/business-consulting-logo-icon-design-template-vector-22318851.jpg',
      img: 'https://weareegg.co.za/media/catalog/product/cache/cd323204adbc90346956a7797c460c7b/t/l/tlt10461_1_1.jpg',
    },
    {
        id: 40,
      city: 'Mens',
      country: 'Floral Lace Harness Lingerie Set',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://cdn.dribbble.com/users/1948198/screenshots/4377223/dribble.gif',
    },
    {
      id: 41,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt0ixO5nE7qYrZ7-wYylFh_2RvxpRs_IW_eg&usqp=CAU',
    },
    {
      id: 42,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://m.media-amazon.com/images/I/41iPvfbxP8L._SS250_.jpg',
    },
    {
        id: 43,
      city: 'Shop - Gadgets',
      country: 'summer v dress',
      p_logo: 'https://cdn2.vectorstock.com/i/1000x1000/88/51/business-consulting-logo-icon-design-template-vector-22318851.jpg',
      img: 'https://weareegg.co.za/media/catalog/product/cache/cd323204adbc90346956a7797c460c7b/t/l/tlt10461_1_1.jpg',
    },
    {
        id: 44,
      city: 'Mens',
      country: 'Floral Lace Harness Lingerie Set',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://cdn.dribbble.com/users/440777/screenshots/1591295/shoping.gif',
    },
    {
      id: 1,
    city: 'Home & Deco.',
    country: 'Rabbit Print Cami PJ Set With Eye Cover',
    p_logo: 'https://www.designhill.com/resize_img.php?atyp=page_file&pth=ft_ca_ct||259||contestfile_1&flp=1626068668-181804171260ebd6bcf116b5-27635942.jpg',
    img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/164857bee1/plain-strappy-tiered-dress.jpg',
  },
  {
      id: 2,
    city: 'Shop - Gadgets',
    country: 'summer v dress',
    p_logo: 'https://cdn2.vectorstock.com/i/1000x1000/88/51/business-consulting-logo-icon-design-template-vector-22318851.jpg',
    img: 'https://weareegg.co.za/media/catalog/product/cache/cd323204adbc90346956a7797c460c7b/t/l/tlt10461_1_1.jpg',
  },
  {
      id: 3,
    city: 'Mens',
    country: 'Floral Lace Harness Lingerie Set',
    p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
    img: 'https://c.tenor.com/tkbRMbqhR2UAAAAC/app-online-store.gif',
  },
  {
      id: 4,
    city: 'Womens',
    country: 'ladies striped T-SHIRT',
    p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
    img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/3080020b4c/mens-crew-t-shirt.jpg',
  },
  {
      id: 5,
    city: 'Moscow',
    country: 'Mens Rillogio sweater',
    p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
    img: 'https://www.yde.co.za/media/product/424/red-printed-track-pants-563.jpg',
  },
  {
      id: 6,
      city: 'Home & Deco.',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
    },
    {
      id: 7,
      city: 'Shop - Gadgets',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
    },
    {
      id: 8,
      city: 'Mens',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 9,
      city: 'Womens',
      country: 'Mens Rillogio sweater',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://blog.bizvibe.com/wp-content/uploads/2020/03/top-clothing-retailers.jpg',
    },
    {
      id: 10,
      city: 'Moscow',
      country: 'Russia',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.unsplash.com/photo-1576723417715-6b408c988c23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amV3ZWxyeSUyMHN0b3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80',
    },
    {
      id: 11,
      city: 'Home & Deco.',
      country: 'Furniture',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2020/10/13/1/CI_Ilya_Zabanov-mastersandforbes-livingroom-Image1.jpg.rend.hgtvcom.966.725.suffix/1602599983799.jpeg',
    },
    {
      id: 12,
      city: 'Shop - Gadgets',
      country: 'Tech',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.autods.com/OfficialSite/New/20201103091044/The-Best-10-Trending-Tech-Gadgets-Dropshipping-Products-To-Sell-in-2021-1024x576.png',
    },
    {
      id: 13,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 14,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 15,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 16,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 17,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 18,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 19,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 20,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 21,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 22,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 23,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 24,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 25,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 26,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 27,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 28,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 29,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 30,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 31,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 32,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 33,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 34,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 35,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 36,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 37,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 38,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
        id: 39,
      city: 'Shop - Gadgets',
      country: 'summer v dress',
      p_logo: 'https://cdn2.vectorstock.com/i/1000x1000/88/51/business-consulting-logo-icon-design-template-vector-22318851.jpg',
      img: 'https://weareegg.co.za/media/catalog/product/cache/cd323204adbc90346956a7797c460c7b/t/l/tlt10461_1_1.jpg',
    },
    {
        id: 40,
      city: 'Mens',
      country: 'Floral Lace Harness Lingerie Set',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.eliteoccasions.co.za/content/images/thumbs/0022090_striped-button-through-shirt-dress-without-belt.jpeg',
    },
    {
      id: 41,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
      id: 42,
      city: 'Mens',
      country: 'Clothing',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://images.pexels.com/photos/3768005/pexels-photo-3768005.jpeg?cs=srgb&dl=pexels-william-mattey-3768005.jpg&fm=jpg',
    },
    {
        id: 43,
      city: 'Shop - Gadgets',
      country: 'summer v dress',
      p_logo: 'https://cdn2.vectorstock.com/i/1000x1000/88/51/business-consulting-logo-icon-design-template-vector-22318851.jpg',
      img: 'https://weareegg.co.za/media/catalog/product/cache/cd323204adbc90346956a7797c460c7b/t/l/tlt10461_1_1.jpg',
    },
    {
        id: 44,
      city: 'Mens',
      country: 'Floral Lace Harness Lingerie Set',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.eliteoccasions.co.za/content/images/thumbs/0022090_striped-button-through-shirt-dress-without-belt.jpeg',
    }
    

];

  export function getProducts() {
    return products;
  }