const slides = [
    {
      city: 'Home & Deco.',
      country: 'Computer, Office and Supplies',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTP6qaemZi4ajORS9cy2pghbucnwMKitr-L0Z6I8GB0sd55LMHqxLQe3WhwnyxUEc2oz6LMQKuagB7wP-Bkikk7YvQXcTRWHqOlEGBMePpq-aNcNtiTPyWn&usqp=CAE',
    },
    {
      city: 'Shop - Gadgets',
      country: 'Computer, Office and Supplies',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcScQFfGDOIVTijxwDMe_X_WPNI6V73s6ntY1RYmyFLiq2X9qY3LfI4FW_EMGydVFgCevmArGGi8-hcTnuVU_im2x1xdmCFQIVBxiZCoktSDn4qNIf8cZtmvPA&usqp=CAE',
    },
    {
      city: 'Mens',
      country: 'Computer, Office and Supplies',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQMiAKXFxAR1ZIZF-OD0AKc5el2gSvYArGr26n32v8ZASEiANUrITVEnamR6-TxKbiPVWJS6idYVo-V4mXFe417djHp7VxHtX1zzbp8nTg&usqp=CAE',
    },
    {
      city: 'Womens',
      country: 'Clothing, Shoes',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.picknpayclothing.co.za/pub/media/catalog/product/cache/703330dce2423b988bd647d4920a16c3/image/3080020b4c/mens-crew-t-shirt.jpg',
    },
    {
      city: 'Moscow',
      country: 'Clothing, Shoes',
      p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
      img: 'https://www.yde.co.za/media/product/424/red-printed-track-pants-563.jpg',
    },
    {
        city: 'Home & Deco.',
        country: 'Clothing, Shoes',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://image.tfgmedia.co.za/image/1/process/259x259?source=https://cdn.tfgmedia.co.za/02/ProductImages/57693082.jpg',
      },
      {
        city: 'Shop - Gadgets',
        country: 'Jewellery',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://www.glencara.com/media/catalog/product/cache/e81f9f892d50e9a3f9d2940976635e4e/P/7/P797-Y-D_1_images.jpg',
      },
      {
        city: 'Mens',
        country: 'Jewellery',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSySbcjAVDVm7H60VKHaA5Dkxw0pm5oYJaHQETFtrOVRVnqd3yOisOmfKouj-R3PP4OFuAkP_5cuZe9AxqGc51m0au63XlTh4x6fxTdmobDRl7Dz-gW7etY&usqp=CAE',
      },
      {
        city: 'Womens',
        country: 'Jewellery',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSpaiuQly5Hs4RhLhc30EBDNBjRGxRtAlSgcY9numGp12iLVrG5HiMkb3ui3wwI9a3P9XAZ0eH4yKqOx0VIYcqoFpa1dBSfJ0_tocnKMXm7jHCzn5BCTtbo&usqp=CAE',
      },
      {
        city: 'Moscow',
        country: 'Beauty and Health',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRAWlXP_gGKQvmiyyIuLWZpOfoeATIfWrBy5or43vztfMKit1XhW5neNmryBa8E-cEwIuAGI2f17SgdLP0yST5qnqJF4pryWxREWQXY4BWeUD73m09dT8TF&usqp=CAE',
      },
      {
        city: 'Home & Deco.',
        country: 'Beauty and Health',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTJ-DSpCRYwNWC-PtsKFV3oxxvFf0OSsi6DtXerZ5WIylkF-XkQm_Os315TjWBK2EA2Ky7HrSGZCEK-dFZyUdzgFl9t1vSdLbcfJz5EphTyc58qd1tPVtqpZA&usqp=CAE',
      },
      {
        city: 'Shop - Gadgets',
        country: 'Beauty and Health',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTSxHj4j0CTQYbJjQt_D3KVeJjOrNFBRI96_VrLKWy37HS1LivWnMHr9-u4BL-0AdClLYv9uUKLRqdutVRZxEa4BLIdvcEZeYp2ra9wKdjqjNeD-fv6_tSvWA&usqp=CAE',
      },
      {
        city: 'Mens',
        country: 'Sports & Outdoors',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSiibBFjr7TeG7tsLq-qv6vmp4b86x04EhhyZ4lbjj2oEEWhkg3VZZa7SZD_hFvzNrs2hWRODrYBsM_jNRNI02Cc3JYYYnXph0BHsMzTtCpKIQr4BJGwcMRuw&usqp=CAE',
      },
      {
        city: 'Womens',
        country: 'Sports & Outdoors',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTCQ5U1cgregEoMEGqGXPiKXdR10Xq5Tf8pY3yKg4ap651Rlbuln0JX_fA3K6UBTlritgfkaIdVHorRNcVFmbdUUFLQ4bM63FrhYu9YKAdkJRVbSuKB4Xk0BA&usqp=CAE',
      },
      {
        city: 'Moscow',
        country: 'Sports & Outdoors',
        p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
        img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSUSNquA77kehUe8sjc_ILxBKVOCLy-mvLzt8-YsGM0ubDaJrHF7QAjgbHofLLbXMFv7oO8tCw2OGh6enw-A0Sa6k6wGvS1nTOksmyYmbrTT1MxgvvXThabCQ&usqp=CAE',
      },
      {
          city: 'Home & Deco.',
          country: 'Home Improvement',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTPGhtvvNQu9mqpFWkGGiiQ-fVA1BeqCP4wEIHLW9EY56HHyjTY0GWRSm8NEK5t3TGrYVAJ_9xXuxcR_2CSpFcxlDhZFDrKUf6dHpXL6rHNGyEMkQnq_xFh&usqp=CAE',
        },
        {
          city: 'Shop - Gadgets',
          country: 'Home Improvement',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTXBuozSaPzYcTJZVAZ-2ud3uFhY0N7D13DhXH7dPxCRMTQ4m0b-z24lpXqokmVVPJz0SAdnjok3Yne17VnSzMAIYw1xQOGrRXMwHEtuTIfrB2OMRBaxsEW1Q&usqp=CAE',
        },
        {
          city: 'Mens',
          country: 'Home Improvement',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ-V-EXTbNwF6M4MqTy3ZVaED1WZOFYlwHN_X802xgQaflM4397ezG_4HnqGGDb2B4zixwNnvgnyrYitB06fqn2stu1AlcE6MB4vnK5H7c6&usqp=CAE',
        },
        {
          city: 'Womens',
          country: 'Automobiles and Motorcycles Parts',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://ae01.alicdn.com/kf/S4264b1431674457782f1079615a98deb2/HomChee-Monitor-Rotation-mount-For-Tesla-Model-3-Model-Y-Retrofit-Four-directional-Central-control-Display.jpg_Q90.jpg_.webp',
        },
        {
          city: 'Moscow',
          country: 'Automobiles and Motorcycles Parts',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://ae01.alicdn.com/kf/S41e361098f5949909fa4146a244d686bM/Car-Neck-Headrest-Pillow-Rest-Head-Support-Cushion-Car-Breathable-Memory-Foam-Slow-Rebound-Guard-Car.jpg_Q90.jpg_.webp',
        },
        {
          city: 'Home & Deco.',
          country: 'Automobiles and Motorcycles Parts',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://ae01.alicdn.com/kf/Se2fdf621a63645d587ea994933095471p/TPU-Key-Case-Cover-For-Kia-Sportage-Cerato-Optima-K2-K3-K4-K5-Rio-Picanto-K2.jpg_Q90.jpg_.webp',
        },
        {
          city: 'Shop - Gadgets',
          country: 'Kids,Toys and Play Equipement',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://ae01.alicdn.com/kf/Sca3e2c1a5dd44f3a99cc47543cffa76fz/2022Baby-Nappy-Changing-Bags-Changing-Station-Portable-Baby-Bed-Travel-Bassinet-Folding-Crib-Shade-Cloth-Changing.jpg_Q90.jpg_.webp',
        },
        {
          city: 'Mens',
          country: 'Kids,Toys and Play Equipement',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://ae01.alicdn.com/kf/S2048710a51e44805890fc2a94cc7ce96E/Sunveno-Ergonomic-Baby-Carrier-Baby-Kangaroo-Child-Hip-Seat-Tool-Baby-Holder-Sling-Wrap-Backpacks-Baby.jpg_Q90.jpg_.webp',
        },
        {
          city: 'Womens',
          country: 'Kids,Toys and Play Equipement',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://ae01.alicdn.com/kf/S7ad2fe0876784900b10f815c648d3682w/100-170-CM-Children-Play-Water-Mat-Summer-Beach-Inflatable-Water-Spray-Pad-Outdoor-Game-Toy.jpg_Q90.jpg_.webp',
        },
        {
          city: 'Moscow',
          country: 'Electronics',
          p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
          img: 'https://i.ebayimg.com/thumbs/images/g/ZEUAAOSw85hgBnYe/s-l225.webp',
        },
        {
            city: 'Home & Deco.',
            country: 'Electronics',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://ae01.alicdn.com/kf/S83f3e181733c40d8b107e97bcc7c099cW/Wireless-Lavalier-Microphone-Lapel-Mini-Mic-Portable-Noise-Reduction-Short-Video-Recording-For-iPhone-Type-C.jpg_Q90.jpg_.webp',
          },
          {
            city: 'Shop - Gadgets',
            country: 'Electronics',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://ae01.alicdn.com/kf/Sc3026a093ecb422dbe4c91d84c92a14bY/KIWI-design-For-Oculus-Quest-2-Elite-Strap-Adjustable-Head-Strap-Increase-Supporting-Improve-Comfort-Virtual.jpg_Q90.jpg_.webp',
          },
          {
            city: 'Mens',
            country: 'Phones & Accessories',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcToxPl_cW7dVgPOqUD9nkuN5kCo4-pJ429hfzJYHGhvFDIEDaLagJR3_XBl9Ib-AkPLqWFQ0fwsRJXxaPsR5-j3VDNOg1InLwFh8Ce8yASZZIs0uWFSKmaWNA&usqp=CAE',
          },
          {
            city: 'Womens',
            country: 'Phones & Accessories',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSMg07x4wmDsEm0FMtoY4JQ2Nil8l8n2qI4vv_e_otdGu6Mi2JBz_PGRGY-ijGyYfRlmTTONJA0A5BI18Nr0WAjO5ZYicNEpUaRGn25pAewZDhszGUsecnDUgo&usqp=CAE',
          },
          {
            city: 'Moscow',
            country: 'Phones & Accessories',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQYnZiVzzvfoES7KLUDyZEPQXlL-Bx8rf-Nr89qU7ezZxr1Y7S40gmHAdvbL1ldMMUDR1vA1RLGa0bemDkrBBs7sWihMp0tO4PCynioWvVezUTekNbUOQcykw&usqp=CAE',
          },
          {
            city: 'Home & Deco.',
            country: 'Automation - Home',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://media.digikey.com/Photos/Delta%20Photos/ASD-B2-2023-B.jpg',
          },
          {
            city: 'Shop - Gadgets',
            country: 'Automation - Industrial',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://media.takealot.com/covers_images/8417cde0d00947e6a0f940b0d00629e7/s-pdpxl.file',
          },
          {
            city: 'Mens',
            country: 'Automation - General',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://media.digikey.com/Photos/Panasonic%20Photos/MHMD042S1U.jpg',
          },
          {
            city: 'Womens',
            country: 'Media Art and Entertainment',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR3AnXp2FfRVH7gAcOfsnRQFRfKdNGWlwjHuSBBnlrNqQzgqyeYwmZIVVPsZb8CcHYy_hw7aT7Mn797cvdjCI0Fvx4FD-FlRg',
          },
          {
            city: 'Moscow',
            country: 'Media Art and Entertainment',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTkEV9xsDpuAC-B3Np5VEf_juEEKzX7FvjjLeIXJ7PBuyMtV0yqt1QGgfTI1pDJ15s4KviflHBlqAtLHrgf2bH5XJaUo89t615oNIY_UpPM&usqp=CAE',
          },
          {
            city: 'Home & Deco.',
            country: 'Media Art and Entertainment',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTZ8sBV3mQ_a8lcP-u5RAfXcEMapip2Z3bf7Wao9d_HnUo4mcrQpJHa5KVrQbFF7_qFBbmwuSpG4B2pLrl0Bz_yb8AlXT5BHs-dfos3oqumh0HjWiF7dnxGtw&usqp=CAE',
          },
          {
            city: 'Shop - Gadgets',
            country: 'Games and Puzzles',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQBSbnUwH-y9itLw6RO7RtIdl_xjSTdIXDyx8BuAhUUFEsxC4aYVz25SknowBJsGn1HU1CRJCt9MnTmC7CR_Ty6T34gs6hv1RmA7Q43RjI',
          },
          {
            city: 'Mens',
            country: 'Games and Puzzles',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://media.takealot.com/covers_images/42c9f89d218c40e0bc7fb9bc0c1899f1/s-list.file',
          },
          {
            city: 'Womens',
            country: 'Games and Puzzles',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://media.takealot.com/covers_images/4e7e503e0b274f3b8c98f523670c59df/s-list.file',
          },
          {
            city: 'Moscow',
            country: 'Arts and Crafts',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://media.takealot.com/covers_images/e8360a6a01344827bbdecd9c404cd4cd/s-list.file',
          },
          {
            city: 'Moscow',
            country: 'Arts and Crafts',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://media.takealot.com/covers_images/9fbe9585df4c494ab6483a7307a75e7b/s-list.file',
          },
          {
            city: 'Moscow',
            country: 'Arts and Crafts',
            p_logo: 'https://logos-world.net/wp-content/uploads/2020/09/Starbucks-Logo.png',
            img: 'https://assets0.mirraw.com/images/9171656/DC0585-1_thumb.jpg?1624770680',
          },
  ];

  export default slides